-name : Docker host configuration
  hosts: docker
  remote_user: ubuntu
  become: yes


  tasks: 
    - name : 1.1.1 Ensure a separate partition for containers has been created (Automated)
    command : if  grep '/var/lib/docker\s' /proc/mounts ; then printf "\033[1;32m [PASS] \033[0m\n" ; else printf "\033[1;33m [WARN] \033[0m\n" ; fi
    - name : 1.1.2 Ensure only trusted users are allowed to control Docker daemon
    command : echo "Users= $(getent group docker)"
    command : printf "\033[1;32m[INFO]:\033[0m You should remove any untrusted users from the docker group using command sudo gpasswd -d <your-user> docker or add trusted users to the docker group using command sudo usermod -aG docker <your-user>. You should not create a mapping of sensitive directories from the host to container volumes."
    -name : 1.1.3 Ensure auditing is configured for the Docker daemon (Automated)
    apt:
      name: git
      state: present
    command: if sudo auditctl -l | grep /usr/bin/dockerd ; then echo "hahaha"; else printf "\033[1;31m [ERROR] \033[0m\n"; fi


