- name : Docker host configuration
  hosts: localhost
  remote_user: ubuntu
  become: yes
  tasks:   
    - name : 2.1 Run the Docker daemon as a non-root user, if possible (Manual)
      script: /home/hamza/memoire/cis/scripts/check2.1 > /tmp/log

    - name : 2.5 Ensure insecure registries are not used (Automated)
      script: /home/hamza/memoire/cis/scripts/check2.5 >> /tmp/log

    - name : 2.6 Ensure aufs storage driver is not used (Automated)
      script: /home/hamza/memoire/cis/scripts/check2.6 >> /tmp/log

    - name : 2.7 Ensure TLS authentication for Docker daemon is configured (Automated)
      script: /home/hamza/memoire/cis/scripts/check2.7 >> /tmp/log

    - name : 2.8 Ensure the default ulimit is configured appropriately (Manual)
      script: /home/hamza/memoire/cis/scripts/check2.8 >> /tmp/log

    - name : 2.9 Enable user namespace support (Automated)
      script: /home/hamza/memoire/cis/scripts/check2.9 >> /tmp/log

    - name : 2.10 Ensure the default cgroup usage has been confirmed (Automated)
      script: /home/hamza/memoire/cis/scripts/check2.10 >> /tmp/log

    - name : 2.11 Ensure base device size is not changed until needed (Automated)
      script: /home/hamza/memoire/cis/scripts/check2.11 >> /tmp/log

    - name : 2.12 Ensure that authorization for Docker client commands is enabled (Automated)
      script: /home/hamza/memoire/cis/scripts/check2.12 >> /tmp/log

    - name : 2.13 Ensure centralized and remote logging is configured (Automated)
      script: /home/hamza/memoire/cis/scripts/check2.13 >> /tmp/log

    - name : 2.14 Ensure containers are restricted from acquiring new privileges (Automated)
      script: /home/hamza/memoire/cis/scripts/check2.14 >> /tmp/log

    - name : 2.15 Ensure live restore is enabled (Automated)
      script: /home/hamza/memoire/cis/scripts/check2.15 >> /tmp/log

    - name : 2.16 Ensure Userland Proxy is Disabled (Automated)
      script: /home/hamza/memoire/cis/scripts/check2.16 >> /tmp/log

    - name : 2.17 Ensure that a daemon-wide custom seccomp profile is applied if appropriate (Manual)
      script: /home/hamza/memoire/cis/scripts/check2.17 >> /tmp/log

    - name : 2.18 Ensure that experimental features are not implemented in production (Automated)
      script: /home/hamza/memoire/cis/scripts/check2.18 >> /tmp/log

  

      