- name : Docker host configuration
  hosts: localhost
  remote_user: ubuntu
  become: yes
  vars: 
    path: /home/khirou/Desktop/pfe/software/cis/
  tasks:   
    - name : executing CIS number 2
      shell: "{{ path }}/check2.{{ item }}.sh >> /tmp/log2"
      loop:
        - 1
        - 2
        - 3
        - 4
        - 5
        - 6
        - 7
        - 8
        - 9
        - 10
        - 11
        - 12
        - 13
        - 14
        - 15
        - 16
        - 17
        - 18
