- name : Docker host configuration
  hosts: localhost
  remote_user: ubuntu
  become: yes
  vars: 
    path: /home/khirou/Desktop/pfe/software/cis/
  tasks:   
    - name : executing CIS number 3
      shell: "{{ path }}/check3.{{ item }}.sh >> /tmp/log3"
      loop:
        - 1
        - 2
        - 3
        - 4
        - 5
        - 6
        - 7
        - 8
        - 9
        - 10
        - 11
        - 12
        - 13
        - 14
        - 15
        - 16
        - 17
        - 18
        - 19
        - 20
        - 21 
        - 22
        - 23
        - 24
