- name : Docker host configuration
  hosts: localhost
  remote_user: ubuntu
  become: yes
  vars: 
    path: /home/khirou/Desktop/pfe/software/cis/
  tasks:   
    - name : executing CIS number 11
      shell: "{{ path }}/check11.{{ item }}.sh >> /tmp/log11"
      loop:
        - 1
        - 2
        - 3
        - 4
        - 5
        - 6
        - 7
        - 8
        - 9
        - 10
        - 11

